### ISSUE TITLE
Todos persistence

### ISSUE THREAD

**Issue by pteasima** [baddazi/TodoList#3]
We might switch to Firestore or similar at some point, but for now lets keep it simple and perstist todos locally on disk.

Deliverables:
 - Todos are persisted in a JSON file in the app's documents directory.
 - Persisted todos are loaded next time the app starts.
 - A PR is created and ready for review, @pteasima is assigned as reviewer

- organize yourself
- mention @pteasima in a comment on this issue if you have technical questions. Don't hesitate to ask those.

**Comment by baddazi** [comment]
@pteasima I have some questions:

1.  In app I use NavigationView  then I saw that TableView  it is often used for similar purposes. What is better ? 

2.  NavigationBarTitle and NavigationBarItem (button) looks wierd. If you scroll down it's look good but in default position the button is too high  compare to title. I found some solution on web, but its look to unbelievably and complex. 

3.  Background of items (todo) have diffretn background then screen. This problem may be caused by using a NavigationView instead of a TableView.  It's clear to me that the background can be set to any color, but I was wondering if the background just has to be set, or it's caused by some ignorance or error in the code.

Thx for answer.

**Comment by pteasima** [comment]
@baddazi I'll answer later. If you wanna continue, just create new branch from `feature/todos-list`. We can rebase against development later once #5 is merged.

**Comment by pteasima** [comment]
> 1. In app I use NavigationView  then I saw that TableView  it is often used for similar purposes. What is better ?

Im assuming by `TableView` you mean `UITableView`. `UITableView` and `NavigationView` are unrelated.

There are 2 view frameworks used on iOS - SwiftUI and UIKit. UIKit is the older technology that parts of SwiftUI are built on. You rarely have to interact with UIKit. `NavigationView` is what gives you the top navigation bar and allows you to do "push" navigation (new screen animates in from the right, you can go back using back button or swiping from left edge). `NavigationView`s equivalent in UIKit would be `UINavigationController`. `List` is what allows you to display a scrollable list of content. Its UIKit equivalent would be `UITableView`. **tl;dr** you were correct to use `NavigationView`, but your question about `TableView` showed that theres some confussion, lmk if its now cleared up.

> 2. NavigationBarTitle and NavigationBarItem (button) looks wierd. If you scroll down it's look good but in default position the button is too high  compare to title. I found some solution on web, but its look to unbelievably and complex.

I think thats just the default "large title style" and is actually the desired behavior. But hard to tell without a screenshot.

> 3. Background of items (todo) have diffretn background then screen. This problem may be caused by using a NavigationView instead of a TableView.  It's clear to me that the background can be set to any color, but I was wondering if the background just has to be set, or it's caused by some ignorance or error in the code.

Again, pics or it didn't happen 😀 A lot of this can just be default iOS design. I'll review code now so will let you know if I see anything wrong.


Overall great questions but I assume you put them here for lack of a better place (they seem unrelated to this issue). Id say ask on the PR, or when there no better way to ask, ask on Zoom chat.
